import { useState } from "react";
import {
  Card,
  Tag,
  Code,
  Grid,
  PageWrap,
  Divider,
  SectionTitle,
  EyebrowLabel,
} from "../components/ui.jsx";

const FLOW_STEPS = [
  {
    id: 1,
    icon: "📝",
    label: "Math Input",
    desc: "A user writes a calculus expression — differentiation, integration, limit, gradient, etc.",
    color: "#06B6D4",
    example: `cs.solve({
  op: "diff",
  var: "x",
  expr: createFraction(
    [createTerm(1, {x: 2}), createTerm(3, {x:1})],
    [createTerm(1)]
  )
})`,
  },
  {
    id: 2,
    icon: "∂",
    label: "SLaNg Encodes",
    desc: "SLaNg's createTerm / createFraction build a structured tree object. No LaTeX, no strings — pure structured data.",
    color: "#A855F7",
    example: `// SLaNg tree object
{
  numi: {
    terms: [
      { coeff: 1, var: { x: 2 } },  // x²
      { coeff: 3, var: { x: 1 } }   // 3x
    ]
  },
  deno: 1   // denominator = 1
}`,
  },
  {
    id: 3,
    icon: "⬡",
    label: "CalculusSolver Tokenizes",
    desc: "The tokenizer serializes the SLaNg tree via DFS into an integer token sequence, with tree-aware positional encoding (depth, sibling index, path hash).",
    color: "#F59E0B",
    example: `// DFS token sequence from tree
// x² + 3x → [POLY, TERM:1:x:2, TERM:3:x:1, END]
const tokens   = dfsSerialize(slangTree);
const positions = encodeTreePosition(tokens);
// position = (depth, siblingIdx, pathHash)`,
  },
  {
    id: 4,
    icon: "🧠",
    label: "Model Predicts",
    desc: "4-component ML model: Tree Encoder reads it, Rule Head decides which calculus rule applies (chain rule, product rule…), Tree Decoder generates the output token-by-token with a validity mask that makes syntactically wrong answers impossible.",
    color: "#EF4444",
    example: `encoder_out = tree_encoder(tokens, positions)
rule_logits = rule_head(encoder_out)
# → "power_rule" for this expression
decoder_out = tree_decoder(
    encoder_out, rule_ids, prev_tokens
)   # validity mask applied at each step`,
  },
  {
    id: 5,
    icon: "✓",
    label: "SLaNg Verifies",
    desc: "The predicted output SLaNg tree is handed back to slangmath (the SLaNg engine) for numerical verification at 50 random test points. The model predicts; SLaNg proves.",
    color: "#10B981",
    example: `// Post-hoc numerical verification
const correct = evaluateFraction(
  result.expr,
  groundTruth,
  { testPoints: 50 }
);
// slangmath is the ground truth — always.`,
  },
  {
    id: 6,
    icon: "📤",
    label: "Output + Steps",
    desc: "The user receives the solved expression back as a SLaNg object, plus step-by-step human-readable explanations generated by the Step Tracer.",
    color: "#6366F1",
    example: `result = {
  expr:  { numi: { terms: [
             { coeff: 2, var: { x: 1 } },
             { coeff: 3 }
           ]}, deno: 1 },  // 2x + 3
  steps: [
    "Apply power rule to x²: → 2x",
    "Differentiate 3x: → 3"
  ]
}`,
  },
];

export default function HowTheyFitPage() {
  const [active, setActive] = useState(0);
  const step = FLOW_STEPS[active];

  return (
    <PageWrap>
      {/* Page header */}
      <div style={{ marginBottom: 40 }}>
        <EyebrowLabel color="#A855F7">OVERVIEW</EyebrowLabel>
        <h1
          style={{
            margin: "8px 0 10px",
            fontSize: 28,
            fontWeight: 700,
            color: "#F1F5F9",
            letterSpacing: "-0.03em",
            lineHeight: 1.2,
          }}
        >
          How SLaNg &amp; CalculusSolver Work Together
        </h1>
        <p
          style={{
            margin: 0,
            fontSize: 13.5,
            color: "#64748B",
            lineHeight: 1.7,
            maxWidth: 580,
          }}
        >
          Two sister projects from Quantum Logics — SLaNg is the math engine,
          CalculusSolver is the ML brain on top.
        </p>
      </div>

      {/* Hero cards */}
      <Grid cols={2} gap={16} style={{ marginBottom: 36 }}>
        <Card accent="#A855F728">
          <div style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
            <div
              style={{
                fontSize: 30,
                lineHeight: 1,
                flexShrink: 0,
                marginTop: 2,
              }}
            >
              ∂
            </div>
            <div>
              <EyebrowLabel color="#A855F7">Layer 0 — Foundation</EyebrowLabel>
              <div
                style={{
                  color: "#F1F5F9",
                  fontSize: 16,
                  fontWeight: 700,
                  marginBottom: 10,
                }}
              >
                SLaNg Math Library
              </div>
              <p
                style={{
                  margin: 0,
                  fontSize: 12.5,
                  color: "#94A3B8",
                  lineHeight: 1.7,
                }}
              >
                A JavaScript library that represents every calculus expression
                as a structured tree object, performs exact symbolic math
                (differentiate, integrate, simplify, verify), and exports a
                LaTeX converter. It is the ground truth — the tool that never
                lies about math.
              </p>
              <div
                style={{
                  display: "flex",
                  gap: 6,
                  marginTop: 14,
                  flexWrap: "wrap",
                }}
              >
                {[
                  "slang-basic.js",
                  "slang-advanced.js",
                  "slang-extended.js",
                  "slang-convertor.js",
                  "slang-symbolic.js",
                ].map((m) => (
                  <Tag key={m} color="#A855F7">
                    {m}
                  </Tag>
                ))}
              </div>
            </div>
          </div>
        </Card>

        <Card accent="#6366F128">
          <div style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
            <div
              style={{
                fontSize: 30,
                lineHeight: 1,
                flexShrink: 0,
                marginTop: 2,
              }}
            >
              ⬡
            </div>
            <div>
              <EyebrowLabel color="#6366F1">
                Layer 1 — Intelligence
              </EyebrowLabel>
              <div
                style={{
                  color: "#F1F5F9",
                  fontSize: 16,
                  fontWeight: 700,
                  marginBottom: 10,
                }}
              >
                CalculusSolver ML System
              </div>
              <p
                style={{
                  margin: 0,
                  fontSize: 12.5,
                  color: "#94A3B8",
                  lineHeight: 1.7,
                }}
              >
                A Python/JS machine learning system trained to solve calculus
                problems. It never implements any math rules itself — instead it
                learns to <em>predict which SLaNg function to call</em>, then
                hands the answer back to SLaNg for verification. The model is
                the strategist; SLaNg is the judge.
              </p>
              <div
                style={{
                  display: "flex",
                  gap: 6,
                  marginTop: 14,
                  flexWrap: "wrap",
                }}
              >
                {[
                  "Tokenizer",
                  "Tree Encoder",
                  "Rule Head",
                  "Tree Decoder",
                  "Step Tracer",
                ].map((m) => (
                  <Tag key={m} color="#6366F1">
                    {m}
                  </Tag>
                ))}
              </div>
            </div>
          </div>
        </Card>
      </Grid>

      {/* Core design principle callout */}
      <div
        style={{
          background: "linear-gradient(135deg, #6366F10D, #06B6D406)",
          border: "1px solid #6366F128",
          borderLeft: "3px solid #6366F1",
          borderRadius: 10,
          padding: "20px 24px",
          marginBottom: 36,
        }}
      >
        <EyebrowLabel color="#6366F1">Core Design Principle</EyebrowLabel>
        <div
          style={{
            fontSize: 15,
            color: "#F1F5F9",
            fontWeight: 600,
            marginBottom: 8,
            letterSpacing: "-0.01em",
          }}
        >
          "The model predicts what to do. SLaNg verifies whether it is correct."
        </div>
        <p
          style={{
            margin: 0,
            fontSize: 13,
            color: "#94A3B8",
            lineHeight: 1.7,
          }}
        >
          CalculusSolver contains zero calculus logic. It learns to predict
          which SLaNg rule applies at each node in the expression tree, and in
          which order. After generating an answer, it passes the result back to{" "}
          <code style={{ color: "#7DD3FC", fontSize: 12 }}>
            evaluateFraction()
          </code>{" "}
          or <code style={{ color: "#7DD3FC", fontSize: 12 }}>slangmath</code>{" "}
          for numerical verification. The architecture is interpretable by
          design: you can read exactly which rule the model applied at every
          step.
        </p>
      </div>

      <Divider />
      <SectionTitle sub="Click each step to see details and code.">
        End-to-End Data Flow
      </SectionTitle>

      {/* Flow navigator */}
      <div
        style={{
          display: "flex",
          gap: 0,
          marginBottom: 20,
          overflowX: "auto",
          paddingBottom: 1,
        }}
      >
        {FLOW_STEPS.map((s, i) => (
          <div key={s.id} style={{ display: "flex", alignItems: "center" }}>
            <button
              onClick={() => setActive(i)}
              style={{
                padding: "10px 15px",
                border: "none",
                background: i === active ? s.color + "18" : "transparent",
                borderBottom:
                  i === active
                    ? `2px solid ${s.color}`
                    : "2px solid transparent",
                color: i === active ? s.color : "#475569",
                cursor: "pointer",
                fontSize: 11.5,
                whiteSpace: "nowrap",
                transition: "all 0.15s",
                fontFamily: "'IBM Plex Mono', monospace",
                fontWeight: i === active ? 700 : 400,
              }}
              onMouseEnter={(e) => {
                if (i !== active) e.currentTarget.style.color = "#94A3B8";
              }}
              onMouseLeave={(e) => {
                if (i !== active) e.currentTarget.style.color = "#475569";
              }}
            >
              <span style={{ marginRight: 6 }}>{s.icon}</span>
              {s.label}
            </button>
            {i < FLOW_STEPS.length - 1 && (
              <span
                style={{ color: "#1E293B", fontSize: 16, padding: "0 1px" }}
              >
                →
              </span>
            )}
          </div>
        ))}
      </div>

      {/* FIX: Grid is now properly inside the Card */}
      <Card accent={step.color + "35"} style={{ marginBottom: 32 }}>
        <Grid cols={2} gap={22}>
          <div>
            <div
              style={{
                display: "flex",
                gap: 10,
                alignItems: "center",
                marginBottom: 14,
              }}
            >
              <span
                style={{
                  fontSize: 28,
                  lineHeight: 1,
                  width: 44,
                  height: 44,
                  background: step.color + "15",
                  border: `1px solid ${step.color}30`,
                  borderRadius: 10,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  flexShrink: 0,
                }}
              >
                {step.icon}
              </span>
              <div>
                <EyebrowLabel color={step.color}>Step {step.id}</EyebrowLabel>
                <div
                  style={{ fontSize: 15, color: "#F1F5F9", fontWeight: 700 }}
                >
                  {step.label}
                </div>
              </div>
            </div>
            <p
              style={{
                margin: 0,
                fontSize: 13,
                color: "#94A3B8",
                lineHeight: 1.75,
              }}
            >
              {step.desc}
            </p>
          </div>
          <Code>{step.example}</Code>
        </Grid>
      </Card>

      <Divider />

      {/* Responsibility table */}
      <SectionTitle sub="How the two repos divide responsibility.">
        Division of Responsibility
      </SectionTitle>
      <Card>
        <div style={{ overflowX: "auto" }}>
          <table
            style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}
          >
            <thead>
              <tr>
                {["Concern", "SLaNg", "CalculusSolver"].map((h, hi) => (
                  <th
                    key={h}
                    style={{
                      textAlign: "left",
                      padding: "10px 16px",
                      color:
                        hi === 1 ? "#A855F7" : hi === 2 ? "#6366F1" : "#334155",
                      fontSize: 10,
                      letterSpacing: "0.1em",
                      borderBottom: "1px solid #1E293B",
                      fontWeight: 700,
                      textTransform: "uppercase",
                    }}
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {[
                [
                  "Knows calculus rules",
                  "✅ Implements them",
                  "❌ Only predicts which to use",
                ],
                [
                  "Math correctness guarantee",
                  "✅ Exact symbolic engine",
                  "✅ Via SLaNg verification",
                ],
                [
                  "Input/output format",
                  "Defines SLaNg tree format",
                  "Consumes SLaNg trees only",
                ],
                [
                  "New operation support",
                  "Add to slangmath first",
                  "Generate pairs, fine-tune",
                ],
                [
                  "Language",
                  "JavaScript (Node + Browser)",
                  "Python (training) + JS (inference)",
                ],
                [
                  "Training data source",
                  "Ground truth provider",
                  "Consumes SLaNg-verified pairs",
                ],
                [
                  "LaTeX support",
                  "slang-convertor.js ↔ LaTeX",
                  "Imports LaTeX via SLaNg converter",
                ],
                [
                  "Numerical verification",
                  "evaluateFraction() at N points",
                  "Calls SLaNg post-decode",
                ],
              ].map(([concern, slang, cs], i) => (
                <tr
                  key={i}
                  style={{
                    background: i % 2 === 0 ? "transparent" : "#ffffff04",
                    transition: "background 0.1s",
                  }}
                  onMouseEnter={(e) =>
                    (e.currentTarget.style.background = "#ffffff07")
                  }
                  onMouseLeave={(e) =>
                    (e.currentTarget.style.background =
                      i % 2 === 0 ? "transparent" : "#ffffff04")
                  }
                >
                  <td
                    style={{
                      padding: "11px 16px",
                      color: "#94A3B8",
                      fontWeight: 500,
                      borderBottom: "1px solid #0D1624",
                    }}
                  >
                    {concern}
                  </td>
                  <td
                    style={{
                      padding: "11px 16px",
                      color: "#C084FC",
                      borderBottom: "1px solid #0D1624",
                    }}
                  >
                    {slang}
                  </td>
                  <td
                    style={{
                      padding: "11px 16px",
                      color: "#818CF8",
                      borderBottom: "1px solid #0D1624",
                    }}
                  >
                    {cs}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </PageWrap>
  );
}
