import { useState } from "react";
import {
  Card,
  Tag,
  Code,
  Grid,
  PageWrap,
  Divider,
  SectionTitle,
} from "../components/ui.jsx";

const FLOW_STEPS = [
  {
    id: 1,
    icon: "📝",
    label: "Math Input",
    desc: "A user writes a calculus expression — differentiation, integration, limit, gradient, etc.",
    color: "#06B6D4",
    example: `cs.solve({
  op: "diff",
  var: "x",
  expr: createFraction(
    [createTerm(1, {x: 2}), createTerm(3, {x:1})],
    [createTerm(1)]
  )
})`,
  },
  {
    id: 2,
    icon: "∂",
    label: "SLaNg Encodes",
    desc: "SLaNg's createTerm / createFraction build a structured tree object. No LaTeX, no strings — pure structured data.",
    color: "#A855F7",
    example: `// SLaNg tree object
{
  numi: {
    terms: [
      { coeff: 1, var: { x: 2 } },  // x²
      { coeff: 3, var: { x: 1 } }   // 3x
    ]
  },
  deno: 1   // denominator = 1
}`,
  },
  {
    id: 3,
    icon: "⬡",
    label: "CalculusSolver Tokenizes",
    desc: "The tokenizer serializes the SLaNg tree via DFS into an integer token sequence, with tree-aware positional encoding (depth, sibling index, path hash).",
    color: "#F59E0B",
    example: `// DFS token sequence from tree
// x² + 3x → [POLY, TERM:1:x:2, TERM:3:x:1, END]
const tokens   = dfsSerialize(slangTree);
const positions = encodeTreePosition(tokens);
// position = (depth, siblingIdx, pathHash)`,
  },
  {
    id: 4,
    icon: "🧠",
    label: "Model Predicts",
    desc: "4-component ML model: Tree Encoder reads it, Rule Head decides which calculus rule applies (chain rule, product rule…), Tree Decoder generates the output token-by-token with a validity mask that makes syntactically wrong answers impossible.",
    color: "#EF4444",
    example: `encoder_out = tree_encoder(tokens, positions)
rule_logits = rule_head(encoder_out)
# → "power_rule" for this expression
decoder_out = tree_decoder(
    encoder_out, rule_ids, prev_tokens
)   # validity mask applied at each step`,
  },
  {
    id: 5,
    icon: "✓",
    label: "SLaNg Verifies",
    desc: "The predicted output SLaNg tree is handed back to slangmath (the SLaNg engine) for numerical verification at 50 random test points. The model predicts; SLaNg proves.",
    color: "#10B981",
    example: `// Post-hoc numerical verification
const correct = evaluateFraction(
  result.expr,
  groundTruth,
  { testPoints: 50 }
);
// slangmath is the ground truth — always.`,
  },
  {
    id: 6,
    icon: "📤",
    label: "Output + Steps",
    desc: "The user receives the solved expression back as a SLaNg object, plus step-by-step human-readable explanations generated by the Step Tracer.",
    color: "#6366F1",
    example: `result = {
  expr:  { numi: { terms: [
             { coeff: 2, var: { x: 1 } },
             { coeff: 3 }
           ]}, deno: 1 },  // 2x + 3
  steps: [
    "Apply power rule to x²: → 2x",
    "Differentiate 3x: → 3"
  ]
}`,
  },
];

export default function HowTheyFitPage() {
  const [active, setActive] = useState(0);
  const step = FLOW_STEPS[active];

  return (
    <PageWrap>
      <SectionTitle sub="Two sister projects from Quantum Logics — SLaNg is the math engine, CalculusSolver is the ML brain on top.">
        How SLaNg &amp; CalculusSolver Work Together
      </SectionTitle>

      {/* Hero cards */}
      <Grid cols={2} gap={16} style={{ marginBottom: 32 }}>
        <Card accent="#A855F730">
          <div style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
            <div style={{ fontSize: 28, lineHeight: 1 }}>∂</div>
            <div>
              <div
                style={{
                  color: "#A855F7",
                  fontSize: 11,
                  letterSpacing: "0.1em",
                  marginBottom: 4,
                }}
              >
                LAYER 0 — FOUNDATION
              </div>
              <div
                style={{
                  color: "#F1F5F9",
                  fontSize: 16,
                  fontWeight: 700,
                  marginBottom: 8,
                }}
              >
                SLaNg Math Library
              </div>
              <p
                style={{
                  margin: 0,
                  fontSize: 12.5,
                  color: "#94A3B8",
                  lineHeight: 1.65,
                }}
              >
                A JavaScript library that represents every calculus expression
                as a structured tree object, performs exact symbolic math
                (differentiate, integrate, simplify, verify), and exports a
                LaTeX converter. It is the ground truth — the tool that never
                lies about math.
              </p>
              <div
                style={{
                  display: "flex",
                  gap: 6,
                  marginTop: 12,
                  flexWrap: "wrap",
                }}
              >
                {[
                  "slang-basic.js",
                  "slang-advanced.js",
                  "slang-extended.js",
                  "slang-convertor.js",
                  "slang-symbolic.js",
                ].map((m) => (
                  <span
                    key={m}
                    style={{
                      fontSize: 10,
                      padding: "2px 8px",
                      borderRadius: 4,
                      background: "#A855F715",
                      color: "#A855F7",
                      border: "1px solid #A855F730",
                    }}
                  >
                    {m}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </Card>
        <Card accent="#6366F130">
          <div style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
            <div style={{ fontSize: 28, lineHeight: 1 }}>⬡</div>
            <div>
              <div
                style={{
                  color: "#6366F1",
                  fontSize: 11,
                  letterSpacing: "0.1em",
                  marginBottom: 4,
                }}
              >
                LAYER 1 — INTELLIGENCE
              </div>
              <div
                style={{
                  color: "#F1F5F9",
                  fontSize: 16,
                  fontWeight: 700,
                  marginBottom: 8,
                }}
              >
                CalculusSolver ML System
              </div>
              <p
                style={{
                  margin: 0,
                  fontSize: 12.5,
                  color: "#94A3B8",
                  lineHeight: 1.65,
                }}
              >
                A Python/JS machine learning system trained to solve calculus
                problems. It never implements any math rules itself — instead it
                learns to <em>predict which SLaNg function to call</em>, then
                hands the answer back to SLaNg for verification. The model is
                the strategist; SLaNg is the judge.
              </p>
              <div
                style={{
                  display: "flex",
                  gap: 6,
                  marginTop: 12,
                  flexWrap: "wrap",
                }}
              >
                {[
                  "Tokenizer",
                  "Tree Encoder",
                  "Rule Head",
                  "Tree Decoder",
                  "Step Tracer",
                ].map((m) => (
                  <span
                    key={m}
                    style={{
                      fontSize: 10,
                      padding: "2px 8px",
                      borderRadius: 4,
                      background: "#6366F115",
                      color: "#6366F1",
                      border: "1px solid #6366F130",
                    }}
                  >
                    {m}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </Card>
      </Grid>

      {/* The key principle */}
      <div
        style={{
          background: "linear-gradient(135deg, #6366F110, #06B6D408)",
          border: "1px solid #6366F130",
          borderRadius: 10,
          padding: "20px 24px",
          marginBottom: 32,
        }}
      >
        <div
          style={{
            fontSize: 11,
            color: "#6366F1",
            letterSpacing: "0.1em",
            marginBottom: 8,
          }}
        >
          CORE DESIGN PRINCIPLE
        </div>
        <div
          style={{
            fontSize: 15,
            color: "#F1F5F9",
            fontWeight: 600,
            marginBottom: 8,
          }}
        >
          "The model predicts what to do. SLaNg verifies whether it is correct."
        </div>
        <p
          style={{
            margin: 0,
            fontSize: 13,
            color: "#94A3B8",
            lineHeight: 1.65,
          }}
        >
          CalculusSolver contains zero calculus logic. It learns to predict
          which SLaNg rule applies at each node in the expression tree, and in
          which order. After generating an answer, it passes the result back to{" "}
          <code style={{ color: "#7DD3FC", fontSize: 12 }}>
            evaluateFraction()
          </code>{" "}
          or <code style={{ color: "#7DD3FC", fontSize: 12 }}>slangmath</code>{" "}
          for numerical verification. The architecture is interpretable by
          design: you can read exactly which rule the model applied at every
          step.
        </p>
      </div>

      <Divider />
      <SectionTitle sub="Click each step to see details and code.">
        End-to-End Data Flow
      </SectionTitle>

      {/* Flow navigator */}
      <div
        style={{ display: "flex", gap: 0, marginBottom: 20, overflowX: "auto" }}
      >
        {FLOW_STEPS.map((s, i) => (
          <div key={s.id} style={{ display: "flex", alignItems: "center" }}>
            <button
              onClick={() => setActive(i)}
              style={{
                padding: "10px 16px",
                border: "none",
                background: i === active ? s.color + "20" : "transparent",
                borderBottom:
                  i === active
                    ? `2px solid ${s.color}`
                    : "2px solid transparent",
                color: i === active ? s.color : "#475569",
                cursor: "pointer",
                fontSize: 12,
                whiteSpace: "nowrap",
                transition: "all 0.15s",
              }}
            >
              <span style={{ marginRight: 6 }}>{s.icon}</span>
              {s.label}
            </button>
            {i < FLOW_STEPS.length - 1 && (
              <span
                style={{ color: "#1E293B", fontSize: 18, padding: "0 2px" }}
              >
                →
              </span>
            )}
          </div>
        ))}
      </div>

      <Card accent={step.color + "40"} style={{ marginBottom: 32 }}>
        <Grid cols={2} gap={20}>
          <div>
            <div
              style={{
                display: "flex",
                gap: 10,
                alignItems: "center",
                marginBottom: 12,
              }}
            >
              <span style={{ fontSize: 24 }}>{step.icon}</span>
              <div>
                <div
                  style={{ fontSize: 15, color: "#F1F5F9", fontWeight: 700 }}
                >
                  Step {step.id}: {step.label}
                </div>
              </div>
            </div>
            <p
              style={{
                margin: 0,
                fontSize: 13,
                color: "#94A3B8",
                lineHeight: 1.7,
              }}
            >
              {step.desc}
            </p>
          </div>
          <Code>{step.example}</Code>
        </Grid>
      </Card>

      <Divider />

      {/* Relationship summary table */}
      <SectionTitle sub="How the two repos divide responsibility.">
        Division of Responsibility
      </SectionTitle>
      <Card>
        <div style={{ overflowX: "auto" }}>
          <table
            style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}
          >
            <thead>
              <tr>
                {["Concern", "SLaNg", "CalculusSolver"].map((h) => (
                  <th
                    key={h}
                    style={{
                      textAlign: "left",
                      padding: "8px 14px",
                      color: "#475569",
                      fontSize: 10,
                      letterSpacing: "0.1em",
                      borderBottom: "1px solid #1E293B",
                    }}
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {[
                [
                  "Knows calculus rules",
                  "✅ Implements them",
                  "❌ Only predicts which to use",
                ],
                [
                  "Math correctness guarantee",
                  "✅ Exact symbolic engine",
                  "✅ Via SLaNg verification",
                ],
                [
                  "Input/output format",
                  "Defines SLaNg tree format",
                  "Consumes SLaNg trees only",
                ],
                [
                  "New operation support",
                  "Add to slangmath first",
                  "Generate pairs, fine-tune",
                ],
                [
                  "Language",
                  "JavaScript (Node + Browser)",
                  "Python (training) + JS (inference)",
                ],
                [
                  "Training data source",
                  "Ground truth provider",
                  "Consumes SLaNg-verified pairs",
                ],
                [
                  "LaTeX support",
                  "slang-convertor.js ↔ LaTeX",
                  "Imports LaTeX via SLaNg converter",
                ],
                [
                  "Numerical verification",
                  "evaluateFraction() at N points",
                  "Calls SLaNg post-decode",
                ],
              ].map(([concern, slang, cs], i) => (
                <tr
                  key={i}
                  style={{
                    background: i % 2 === 0 ? "transparent" : "#ffffff05",
                  }}
                >
                  <td
                    style={{
                      padding: "10px 14px",
                      color: "#94A3B8",
                      fontWeight: 500,
                    }}
                  >
                    {concern}
                  </td>
                  <td style={{ padding: "10px 14px", color: "#A855F7" }}>
                    {slang}
                  </td>
                  <td style={{ padding: "10px 14px", color: "#6366F1" }}>
                    {cs}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </PageWrap>
  );
}
