import { useState } from "react";
import {
  Card,
  Tag,
  Code,
  Grid,
  PageWrap,
  Divider,
  SectionTitle,
  EyebrowLabel,
  StatBadge,
} from "../components/ui.jsx";

const FLOW_STEPS = [
  {
    id: 1,
    icon: "📝",
    label: "Math Input",
    desc: "A user writes a calculus expression — differentiation, integration, limit, gradient, etc.",
    color: "#22D3EE",
    example: `cs.solve({
  op: "diff",
  var: "x",
  expr: createFraction(
    [createTerm(1, {x: 2}), createTerm(3, {x:1})],
    [createTerm(1)]
  )
})`,
  },
  {
    id: 2,
    icon: "∂",
    label: "SLaNg Encodes",
    desc: "SLaNg's createTerm / createFraction build a structured tree object. No LaTeX, no strings — pure structured data.",
    color: "#C084FC",
    example: `// SLaNg tree object
{
  numi: {
    terms: [
      { coeff: 1, var: { x: 2 } },  // x²
      { coeff: 3, var: { x: 1 } }   // 3x
    ]
  },
  deno: 1   // denominator = 1
}`,
  },
  {
    id: 3,
    icon: "⬡",
    label: "Tokenizes",
    desc: "The tokenizer serializes the SLaNg tree via DFS into an integer token sequence, with tree-aware positional encoding (depth, sibling index, path hash).",
    color: "#F59E0B",
    example: `// DFS token sequence from tree
// x² + 3x → [POLY, TERM:1:x:2, TERM:3:x:1, END]
const tokens    = dfsSerialize(slangTree);
const positions = encodeTreePosition(tokens);
// position = (depth, siblingIdx, pathHash)`,
  },
  {
    id: 4,
    icon: "🧠",
    label: "Model Predicts",
    desc: "4-component ML model: Tree Encoder reads it, Rule Head decides which calculus rule applies, Tree Decoder generates the output with a validity mask that makes syntactically wrong answers impossible.",
    color: "#EF4444",
    example: `encoder_out = tree_encoder(tokens, positions)
rule_logits = rule_head(encoder_out)
# → "power_rule" for this expression
decoder_out = tree_decoder(
    encoder_out, rule_ids, prev_tokens
)   # validity mask applied at each step`,
  },
  {
    id: 5,
    icon: "✓",
    label: "SLaNg Verifies",
    desc: "The predicted output SLaNg tree is handed back to slangmath for numerical verification at 50 random test points. The model predicts; SLaNg proves.",
    color: "#10B981",
    example: `// Post-hoc numerical verification
const correct = evaluateFraction(
  result.expr,
  groundTruth,
  { testPoints: 50 }
);
// slangmath is the ground truth — always.`,
  },
  {
    id: 6,
    icon: "📤",
    label: "Output + Steps",
    desc: "The user receives the solved expression back as a SLaNg object, plus step-by-step human-readable explanations generated by the Step Tracer.",
    color: "#7C6FFF",
    example: `result = {
  expr:  { numi: { terms: [
             { coeff: 2, var: { x: 1 } },
             { coeff: 3 }
           ]}, deno: 1 },  // 2x + 3
  steps: [
    "Apply power rule to x²: → 2x",
    "Differentiate 3x: → 3"
  ]
}`,
  },
];

const RESPONSIBILITY = [
  [
    "Knows calculus rules",
    "✅ Implements them",
    "❌ Only predicts which to use",
  ],
  [
    "Math correctness guarantee",
    "✅ Exact symbolic engine",
    "✅ Via SLaNg verification",
  ],
  [
    "Input / output format",
    "Defines SLaNg tree format",
    "Consumes SLaNg trees only",
  ],
  [
    "New operation support",
    "Add to slangmath first",
    "Generate pairs, fine-tune",
  ],
  [
    "Language",
    "JavaScript (Node + Browser)",
    "Python (training) + JS (inference)",
  ],
  [
    "Training data source",
    "Ground truth provider",
    "Consumes SLaNg-verified pairs",
  ],
  [
    "LaTeX support",
    "slang-convertor.js ↔ LaTeX",
    "Imports LaTeX via SLaNg converter",
  ],
  [
    "Numerical verification",
    "evaluateFraction() at N pts",
    "Calls SLaNg post-decode",
  ],
];

export default function HowTheyFitPage() {
  const [active, setActive] = useState(0);
  const step = FLOW_STEPS[active];

  return (
    <PageWrap>
      {/* ── Page header ───────────────────────────────────────────────── */}
      <div style={{ marginBottom: 48 }}>
        <EyebrowLabel color="#C084FC">SYSTEM OVERVIEW</EyebrowLabel>
        <h1
          style={{
            margin: "10px 0 12px",
            fontSize: 32,
            fontWeight: 700,
            color: "#EFF3FF",
            letterSpacing: "-0.03em",
            lineHeight: 1.15,
            fontFamily: "var(--font-sans)",
          }}
        >
          How SLaNg &amp; CalculusSolver
          <br />
          <span
            style={{
              background: "linear-gradient(90deg, #C084FC, #7C6FFF)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
          >
            Work Together
          </span>
        </h1>
        <p
          style={{
            margin: 0,
            fontSize: 14,
            color: "#3D4D6A",
            lineHeight: 1.75,
            maxWidth: 560,
            fontFamily: "var(--font-sans)",
          }}
        >
          Two sister projects from Quantum Logics — SLaNg is the math engine,
          CalculusSolver is the ML brain on top.
        </p>
      </div>

      {/* ── Hero project cards ────────────────────────────────────────── */}
      <Grid cols={2} gap={16} style={{ marginBottom: 48 }}>
        {/* SLaNg card */}
        <Card
          accent="#C084FC28"
          glow
          style={{ position: "relative", overflow: "hidden" }}
        >
          {/* subtle bg glyph */}
          <div
            aria-hidden
            style={{
              position: "absolute",
              right: 16,
              bottom: 8,
              fontSize: 80,
              lineHeight: 1,
              color: "#C084FC08",
              fontFamily: "var(--font-mono)",
              userSelect: "none",
              pointerEvents: "none",
            }}
          >
            ∂
          </div>

          <div style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
            <div
              style={{
                width: 44,
                height: 44,
                borderRadius: 10,
                flexShrink: 0,
                background: "linear-gradient(135deg, #C084FC20, #C084FC08)",
                border: "1px solid #C084FC30",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontSize: 24,
                color: "#C084FC",
              }}
            >
              ∂
            </div>
            <div>
              <EyebrowLabel color="#C084FC">Layer 0 — Foundation</EyebrowLabel>
              <div
                style={{
                  color: "#EFF3FF",
                  fontSize: 17,
                  fontWeight: 700,
                  marginBottom: 10,
                }}
              >
                SLaNg Math Library
              </div>
              <p
                style={{
                  margin: 0,
                  fontSize: 13,
                  color: "#8B97B8",
                  lineHeight: 1.75,
                }}
              >
                A JavaScript library that represents every calculus expression
                as a structured tree object, performs exact symbolic math
                (differentiate, integrate, simplify, verify), and exports a
                LaTeX converter. It is the ground truth — the tool that never
                lies about math.
              </p>
              <div
                style={{
                  display: "flex",
                  gap: 6,
                  marginTop: 14,
                  flexWrap: "wrap",
                }}
              >
                {[
                  "slang-basic.js",
                  "slang-advanced.js",
                  "slang-extended.js",
                  "slang-convertor.js",
                  "slang-symbolic.js",
                ].map((m) => (
                  <Tag key={m} color="#C084FC">
                    {m}
                  </Tag>
                ))}
              </div>
            </div>
          </div>
        </Card>

        {/* CalculusSolver card */}
        <Card
          accent="#7C6FFF28"
          glow
          style={{ position: "relative", overflow: "hidden" }}
        >
          <div
            aria-hidden
            style={{
              position: "absolute",
              right: 14,
              bottom: 6,
              fontSize: 80,
              lineHeight: 1,
              color: "#7C6FFF08",
              fontFamily: "var(--font-mono)",
              userSelect: "none",
              pointerEvents: "none",
            }}
          >
            ⬡
          </div>

          <div style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
            <div
              style={{
                width: 44,
                height: 44,
                borderRadius: 10,
                flexShrink: 0,
                background: "linear-gradient(135deg, #7C6FFF20, #7C6FFF08)",
                border: "1px solid #7C6FFF30",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontSize: 22,
                color: "#7C6FFF",
              }}
            >
              ⬡
            </div>
            <div>
              <EyebrowLabel color="#7C6FFF">
                Layer 1 — Intelligence
              </EyebrowLabel>
              <div
                style={{
                  color: "#EFF3FF",
                  fontSize: 17,
                  fontWeight: 700,
                  marginBottom: 10,
                }}
              >
                CalculusSolver ML System
              </div>
              <p
                style={{
                  margin: 0,
                  fontSize: 13,
                  color: "#8B97B8",
                  lineHeight: 1.75,
                }}
              >
                A Python/JS machine learning system trained to solve calculus
                problems. It never implements math rules itself — instead it
                learns to{" "}
                <em
                  style={{
                    color: "#7C6FFF",
                    fontStyle: "normal",
                    fontWeight: 600,
                  }}
                >
                  predict which SLaNg function to call
                </em>
                , then hands the answer back to SLaNg for verification. The
                model is the strategist; SLaNg is the judge.
              </p>
              <div
                style={{
                  display: "flex",
                  gap: 6,
                  marginTop: 14,
                  flexWrap: "wrap",
                }}
              >
                {[
                  "Tokenizer",
                  "Tree Encoder",
                  "Rule Head",
                  "Tree Decoder",
                  "Step Tracer",
                ].map((m) => (
                  <Tag key={m} color="#7C6FFF">
                    {m}
                  </Tag>
                ))}
              </div>
            </div>
          </div>
        </Card>
      </Grid>

      {/* ── Quick stats ───────────────────────────────────────────────── */}
      <Grid cols={4} gap={12} style={{ marginBottom: 48 }}>
        <StatBadge value="5M+" label="Training pairs" color="#7C6FFF" />
        <StatBadge value="50" label="Verify test pts" color="#22D3EE" />
        <StatBadge value="8" label="Transformer layers" color="#C084FC" />
        <StatBadge value="30+" label="Calculus rules" color="#F59E0B" />
      </Grid>

      <Divider />

      {/* ── Step-by-step flow ─────────────────────────────────────────── */}
      <SectionTitle sub="Follow the journey from raw math expression to verified solution.">
        End-to-End Flow
      </SectionTitle>

      {/* Step selector pills */}
      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          gap: 6,
          marginBottom: 20,
          padding: "14px 18px",
          background: "#0B0E1A",
          border: "1px solid #1C2438",
          borderRadius: 10,
        }}
      >
        {FLOW_STEPS.map((s, i) => (
          <button
            key={s.id}
            onClick={() => setActive(i)}
            style={{
              display: "flex",
              alignItems: "center",
              gap: 6,
              padding: "7px 14px",
              borderRadius: 6,
              border: `1px solid ${i === active ? s.color + "40" : "#1C2438"}`,
              background: i === active ? s.color + "12" : "transparent",
              color: i === active ? s.color : "#3D4D6A",
              cursor: "pointer",
              fontSize: 12,
              fontWeight: i === active ? 600 : 400,
              transition: "all 0.15s",
              fontFamily: "var(--font-sans)",
              whiteSpace: "nowrap",
            }}
            onMouseEnter={(e) => {
              if (i !== active) {
                e.currentTarget.style.color = "#8B97B8";
                e.currentTarget.style.borderColor = "#1C2438";
              }
            }}
            onMouseLeave={(e) => {
              if (i !== active) {
                e.currentTarget.style.color = "#3D4D6A";
                e.currentTarget.style.borderColor = "#1C2438";
              }
            }}
          >
            <span>{s.icon}</span>
            <span style={{ fontSize: 10, opacity: 0.6 }}>{s.id}.</span>
            {s.label}
          </button>
        ))}
      </div>

      {/* Active step detail card */}
      <Card accent={step.color + "30"} glow style={{ marginBottom: 40 }}>
        <Grid cols={2} gap={24}>
          <div>
            <div
              style={{
                display: "flex",
                gap: 12,
                alignItems: "center",
                marginBottom: 16,
              }}
            >
              <span
                style={{
                  fontSize: 26,
                  lineHeight: 1,
                  width: 46,
                  height: 46,
                  background: step.color + "14",
                  border: `1px solid ${step.color}28`,
                  borderRadius: 10,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  flexShrink: 0,
                }}
              >
                {step.icon}
              </span>
              <div>
                <EyebrowLabel color={step.color}>
                  Step {step.id} of {FLOW_STEPS.length}
                </EyebrowLabel>
                <div
                  style={{ fontSize: 16, color: "#EFF3FF", fontWeight: 700 }}
                >
                  {step.label}
                </div>
              </div>
            </div>
            <p
              style={{
                margin: 0,
                fontSize: 13.5,
                color: "#8B97B8",
                lineHeight: 1.8,
              }}
            >
              {step.desc}
            </p>
          </div>
          <Code>{step.example}</Code>
        </Grid>
      </Card>

      <Divider />

      {/* ── Responsibility table ──────────────────────────────────────── */}
      <SectionTitle sub="How the two repos divide responsibility.">
        Division of Responsibility
      </SectionTitle>

      <Card>
        <div style={{ overflowX: "auto" }}>
          <table
            style={{
              width: "100%",
              borderCollapse: "collapse",
              fontSize: 12.5,
            }}
          >
            <thead>
              <tr>
                {[
                  { h: "Concern", color: "#3D4D6A" },
                  { h: "SLaNg", color: "#C084FC" },
                  { h: "CalculusSolver", color: "#7C6FFF" },
                ].map(({ h, color }) => (
                  <th
                    key={h}
                    style={{
                      textAlign: "left",
                      padding: "12px 18px",
                      color,
                      fontSize: 10,
                      letterSpacing: "0.12em",
                      borderBottom: "1px solid #1C2438",
                      fontWeight: 600,
                      textTransform: "uppercase",
                      fontFamily: "var(--font-mono)",
                    }}
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {RESPONSIBILITY.map(([concern, slang, cs], i) => (
                <tr
                  key={i}
                  style={{
                    background: i % 2 === 0 ? "transparent" : "#ffffff03",
                    transition: "background 0.1s",
                  }}
                  onMouseEnter={(e) =>
                    (e.currentTarget.style.background = "#ffffff06")
                  }
                  onMouseLeave={(e) =>
                    (e.currentTarget.style.background =
                      i % 2 === 0 ? "transparent" : "#ffffff03")
                  }
                >
                  <td
                    style={{
                      padding: "12px 18px",
                      color: "#8B97B8",
                      fontWeight: 500,
                      borderBottom: "1px solid #0F1728",
                    }}
                  >
                    {concern}
                  </td>
                  <td
                    style={{
                      padding: "12px 18px",
                      color: "#C084FC",
                      borderBottom: "1px solid #0F1728",
                      fontFamily: "var(--font-sans)",
                    }}
                  >
                    {slang}
                  </td>
                  <td
                    style={{
                      padding: "12px 18px",
                      color: "#A5B4FC",
                      borderBottom: "1px solid #0F1728",
                      fontFamily: "var(--font-sans)",
                    }}
                  >
                    {cs}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </PageWrap>
  );
}
